<script lang="ts">
  // A 16px item glyph (public/sprites/items/<id>.png, generated by scripts/sprites.py), scaled
  // crisp. A missing file falls back to the unknown blob so a new item never breaks a screen.
  let { id, size = 32 }: { id: string; size?: number } = $props();
  const base = import.meta.env.BASE_URL;
  function fallback(e: Event) {
    const img = e.currentTarget as HTMLImageElement;
    if (!img.src.endsWith('sprites/unknown.png')) img.src = `${base}sprites/unknown.png`;
  }
</script>

<img class="icon" src="{base}sprites/items/{id}.png" alt="" width={size} height={size} onerror={fallback} />

<style>
  .icon {
    image-rendering: pixelated;
    image-rendering: crisp-edges;
    flex: none;
    filter: drop-shadow(2px 2px 0 var(--shade));
  }
</style>
