/**
 * Placeholder items, named for the cell that carries them (Dean, 2026-09-08: word and
 * evolution themed, not generic). Ten items across five hooks and eight effect types:
 * enough to prove the hook system moves the sim, not to be balanced. Ids are stable; only
 * names and descriptions change, so saves and tests keyed by id survive renames.
 * Rarity weights: see RARITY_WEIGHT.
 */
import type { ItemDef, Rarity } from '../engine/types';

export const RARITY_WEIGHT: Readonly<Record<Rarity, number>> = { common: 3, uncommon: 2, rare: 1, mythic: 0.35 };

export const ITEMS: readonly ItemDef[] = [
  {
    id: 'sharp-pen',
    name: 'Flagellum',
    rarity: 'common',
    description: '+8 damage on every word.',
    flavor: 'A lash behind every syllable.',
    hooks: { onWordScored: [{ type: 'addFlat', value: 8 }] },
  },
  {
    id: 'lens',
    name: 'Photoreceptor',
    rarity: 'uncommon',
    description: '+70% damage.',
    flavor: 'It sees where the weak spot is.',
    hooks: { onWordScored: [{ type: 'addMult', value: 0.7 }] },
  },
  {
    id: 'long-fuse',
    name: 'Ribosome',
    rarity: 'rare',
    description: 'Words of 6+ letters deal double damage.',
    flavor: 'Long chains, long proteins.',
    hooks: {
      onWordScored: [{ type: 'condition', when: { kind: 'minLength', value: 6 }, then: [{ type: 'addMult', value: 1 }] }],
    },
  },
  {
    id: 'vowel-magnet',
    name: 'Vacuole',
    rarity: 'common',
    description: 'Vowels are drawn 20% more often, and +3 damage.',
    flavor: 'It stores what you keep running out of.',
    hooks: { onTileDraw: [{ type: 'vowelWeight', value: 1.2 }], onWordScored: [{ type: 'addFlat', value: 3 }] },
  },
  {
    id: 'bandage',
    name: 'Mitosis',
    rarity: 'common',
    description: 'Heal 20 after each encounter.',
    flavor: 'Split, recover, continue.',
    hooks: { onEncounterEnd: [{ type: 'heal', value: 20 }] },
  },
  {
    id: 'thick-skin',
    name: 'Membrane',
    rarity: 'uncommon',
    description: 'Take 4 less damage from every hit.',
    flavor: 'Thicker than it looks.',
    hooks: { onDamageTaken: [{ type: 'reduceDamage', value: 4 }] },
  },
  {
    id: 'rare-ink',
    name: 'Enzyme',
    rarity: 'uncommon',
    description: 'J, Q, X and Z are worth +10 each.',
    flavor: 'It catalyses the awkward letters.',
    hooks: { onWordScored: [{ type: 'letterBonus', letters: 'jqxz', value: 10 }] },
  },
  {
    id: 'leech',
    name: 'Cilia',
    rarity: 'uncommon',
    description: 'Heal 4 on every word of 5+ letters.',
    flavor: 'Every long word sweeps in a little life.',
    hooks: {
      onWordScored: [{ type: 'condition', when: { kind: 'minLength', value: 5 }, then: [{ type: 'heal', value: 4 }] }],
    },
  },
  {
    id: 'spores',
    name: 'Spores',
    rarity: 'common',
    description: 'Deal 6 damage to the enemy at the start of each turn.',
    flavor: 'They drift, they land, they burn.',
    hooks: { onTurnStart: [{ type: 'damageEnemy', value: 6 }] },
  },
  // Pool expansion (Dean, 2026-09-08: the first offer was always the same commons). Fourteen
  // more items from the existing vocabulary; rule-benders wait for new effect types.
  {
    id: 'lysosome',
    name: 'Lysosome',
    rarity: 'common',
    description: 'Words of 4 letters or fewer deal +10.',
    flavor: 'Small, sharp, everywhere.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'maxLength', value: 4 }, then: [{ type: 'addFlat', value: 10 }] }] },
  },
  {
    id: 'pilus',
    name: 'Pilus',
    rarity: 'common',
    description: 'Words containing S deal +8.',
    flavor: 'It grips.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'containsLetter', letters: 's' }, then: [{ type: 'addFlat', value: 8 }] }] },
  },
  {
    id: 'chloroplast',
    name: 'Chloroplast',
    rarity: 'common',
    description: 'Heal 3 at the start of every turn.',
    flavor: 'Sunlight, slowly.',
    hooks: { onTurnStart: [{ type: 'heal', value: 3 }] },
  },
  {
    id: 'cell-wall',
    name: 'Cell Wall',
    rarity: 'common',
    description: 'While below half HP, take 6 less damage from every hit.',
    flavor: 'It stiffens under stress.',
    hooks: { onDamageTaken: [{ type: 'condition', when: { kind: 'hpBelow', fraction: 0.5 }, then: [{ type: 'reduceDamage', value: 6 }] }] },
  },
  {
    id: 'nucleus',
    name: 'Nucleus',
    rarity: 'common',
    description: 'Every vowel in a word is worth +3.',
    flavor: 'The centre holds.',
    hooks: { onWordScored: [{ type: 'letterBonus', letters: 'aeiou', value: 3 }] },
  },
  {
    id: 'plasmid',
    name: 'Plasmid',
    rarity: 'common',
    description: 'Every second turn, +70% damage.',
    flavor: 'Borrowed genes, on loan.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'turnEvery', value: 2 }, then: [{ type: 'addMult', value: 0.7 }] }] },
  },
  {
    id: 'peroxisome',
    name: 'Peroxisome',
    rarity: 'uncommon',
    description: 'Words of 5+ letters deal +15.',
    flavor: 'It breaks things down.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'minLength', value: 5 }, then: [{ type: 'addFlat', value: 15 }] }] },
  },
  {
    id: 'golgi',
    name: 'Golgi Body',
    rarity: 'uncommon',
    description: 'L, N, R, S and T are worth +4 each.',
    flavor: 'It packages the ordinary.',
    hooks: { onWordScored: [{ type: 'letterBonus', letters: 'lnrst', value: 4 }] },
  },
  {
    id: 'centriole',
    name: 'Centriole',
    rarity: 'uncommon',
    description: 'Every third turn, deal 18 damage at the start of the turn.',
    flavor: 'It pulls things apart.',
    hooks: { onTurnStart: [{ type: 'condition', when: { kind: 'turnEvery', value: 3 }, then: [{ type: 'damageEnemy', value: 18 }] }] },
  },
  {
    id: 'tentacle',
    name: 'Tentacle',
    rarity: 'common',
    description: 'Words containing J, Q, X or Z deal double damage.',
    flavor: 'Reach for the awkward ones.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'containsLetter', letters: 'jqxz' }, then: [{ type: 'addMult', value: 1 }] }] },
  },
  {
    id: 'symbiont',
    name: 'Symbiont',
    rarity: 'uncommon',
    description: 'Heal 30 after each encounter, but lose 1 HP at the start of every turn.',
    flavor: 'It eats too.',
    hooks: { onEncounterEnd: [{ type: 'heal', value: 30 }], onTurnStart: [{ type: 'damagePlayer', value: 1 }] },
  },
  {
    id: 'apex',
    name: 'Apex Membrane',
    rarity: 'rare',
    description: 'Words of 7+ letters deal triple damage.',
    flavor: 'The top of the food chain.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'minLength', value: 7 }, then: [{ type: 'addMult', value: 2 }] }] },
  },
  {
    id: 'regeneration',
    name: 'Regeneration',
    rarity: 'rare',
    description: 'Heal 1 whenever you take damage.',
    flavor: 'It grows back.',
    hooks: { onDamageTaken: [{ type: 'heal', value: 1 }] },
  },
  {
    id: 'thin-membrane',
    name: 'Thin Membrane',
    rarity: 'rare',
    description: 'Double damage, but every hit you take hurts 4 more.',
    flavor: 'Nothing between you and the world.',
    hooks: { onWordScored: [{ type: 'addMult', value: 1 }], onDamageTaken: [{ type: 'damagePlayer', value: 4 }] },
  },
  {
    id: 'second-wind',
    name: 'Cyst',
    rarity: 'rare',
    description: 'While below 30% HP, heal 2 whenever you take damage.',
    flavor: 'Harden when it hurts.',
    hooks: {
      onDamageTaken: [{ type: 'condition', when: { kind: 'hpBelow', fraction: 0.3 }, then: [{ type: 'heal', value: 2 }] }],
    },
  },
  // Second expansion (Dean, 2026-09-08: "a ton more"). Still the existing vocabulary, combined
  // into identities: thorns, self-venom for power, chaos for damage, cadence gates, HP gates.
  {
    id: 'microtubule',
    name: 'Microtubule',
    rarity: 'common',
    description: 'Words of 5 letters or fewer deal +40%.',
    flavor: 'Short, straight, strong.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'maxLength', value: 5 }, then: [{ type: 'addMult', value: 0.4 }] }] },
  },
  {
    id: 'cytoplasm',
    name: 'Cytoplasm',
    rarity: 'common',
    description: 'Heal 1 at the start of every turn and 10 after each encounter.',
    flavor: 'The medium itself.',
    hooks: { onTurnStart: [{ type: 'heal', value: 1 }], onEncounterEnd: [{ type: 'heal', value: 10 }] },
  },
  {
    id: 'contractile-vacuole',
    name: 'Contractile Vacuole',
    rarity: 'common',
    description: 'Every second turn, heal 3.',
    flavor: 'Pump, release, repeat.',
    hooks: { onTurnStart: [{ type: 'condition', when: { kind: 'turnEvery', value: 2 }, then: [{ type: 'heal', value: 3 }] }] },
  },
  {
    id: 'osmosis',
    name: 'Osmosis',
    rarity: 'common',
    description: 'While below 70% HP, take 2 less damage from every hit.',
    flavor: 'Pressure finds its level.',
    hooks: { onDamageTaken: [{ type: 'condition', when: { kind: 'hpBelow', fraction: 0.7 }, then: [{ type: 'reduceDamage', value: 2 }] }] },
  },
  {
    id: 'histone',
    name: 'Histone',
    rarity: 'common',
    description: 'B, D and G are worth +3 each.',
    flavor: 'It winds the hard letters tight.',
    hooks: { onWordScored: [{ type: 'letterBonus', letters: 'bdg', value: 3 }] },
  },
  {
    id: 'ribbon',
    name: 'Ribbon',
    rarity: 'common',
    description: 'I, N and G are worth +2 each.',
    flavor: 'It ties things together.',
    hooks: { onWordScored: [{ type: 'letterBonus', letters: 'ing', value: 2 }] },
  },
  {
    id: 'stinger',
    name: 'Stinger',
    rarity: 'common',
    description: 'Words containing K or X deal +12.',
    flavor: 'One sharp point.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'containsLetter', letters: 'kx' }, then: [{ type: 'addFlat', value: 12 }] }] },
  },
  {
    id: 'spine',
    name: 'Spine',
    rarity: 'common',
    description: 'Whenever you take damage, deal 5 back.',
    flavor: 'Touch it and see.',
    hooks: { onDamageTaken: [{ type: 'damageEnemy', value: 5 }] },
  },
  {
    id: 'mucus',
    name: 'Mucus',
    rarity: 'common',
    description: 'Take 2 less damage from every hit.',
    flavor: 'Unpleasant, effective.',
    hooks: { onDamageTaken: [{ type: 'reduceDamage', value: 2 }] },
  },
  {
    id: 'buoyancy',
    name: 'Buoyancy',
    rarity: 'common',
    description: 'Vowels are drawn 30% less often, but +40% damage.',
    flavor: 'Denser. Heavier. Harder to spell.',
    hooks: { onTileDraw: [{ type: 'vowelWeight', value: 0.7 }], onWordScored: [{ type: 'addMult', value: 0.4 }] },
  },
  {
    id: 'chitin-plate',
    name: 'Chitin Plate',
    rarity: 'uncommon',
    description: 'Take 5 less damage from every hit.',
    flavor: 'Armour grown, not worn.',
    hooks: { onDamageTaken: [{ type: 'reduceDamage', value: 5 }] },
  },
  {
    id: 'toxin-sac',
    name: 'Toxin Sac',
    rarity: 'uncommon',
    description: '+60% damage, but every fourth turn one of your tiles turns venomous.',
    flavor: 'You are what you secrete.',
    hooks: {
      onWordScored: [{ type: 'addMult', value: 0.6 }],
      onTurnStart: [{ type: 'condition', when: { kind: 'turnEvery', value: 4 }, then: [{ type: 'venomTiles', count: 1, value: 1 }] }],
    },
  },
  {
    id: 'flagellar-motor',
    name: 'Flagellar Motor',
    rarity: 'uncommon',
    description: '+8 damage on every word, but every fifth turn the grid scrambles.',
    flavor: 'It spins. Everything spins.',
    hooks: {
      onWordScored: [{ type: 'addFlat', value: 8 }],
      onTurnStart: [{ type: 'condition', when: { kind: 'turnEvery', value: 5 }, then: [{ type: 'scramble' }] }],
    },
  },
  {
    id: 'hemoglobin',
    name: 'Hemoglobin',
    rarity: 'uncommon',
    description: 'While below half HP, +80% damage.',
    flavor: 'It carries what you need, when you need it.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'hpBelow', fraction: 0.5 }, then: [{ type: 'addMult', value: 0.8 }] }] },
  },
  {
    id: 'antibody',
    name: 'Antibody',
    rarity: 'uncommon',
    description: 'On even turns, take 8 less damage from every hit.',
    flavor: 'It learned last time.',
    hooks: { onDamageTaken: [{ type: 'condition', when: { kind: 'turnEvery', value: 2 }, then: [{ type: 'reduceDamage', value: 8 }] }] },
  },
  {
    id: 'catalase',
    name: 'Catalase',
    rarity: 'uncommon',
    description: 'Words of 5+ letters deal +50%.',
    flavor: 'Faster than it has any right to be.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'minLength', value: 5 }, then: [{ type: 'addMult', value: 0.5 }] }] },
  },
  {
    id: 'lure',
    name: 'Lure',
    rarity: 'uncommon',
    description: 'Words containing Y deal +10 and heal 2.',
    flavor: 'Why? Exactly.',
    hooks: {
      onWordScored: [{ type: 'condition', when: { kind: 'containsLetter', letters: 'y' }, then: [{ type: 'addFlat', value: 10 }, { type: 'heal', value: 2 }] }],
    },
  },
  {
    id: 'membrane-pump',
    name: 'Membrane Pump',
    rarity: 'uncommon',
    description: 'Heal 1 whenever you take damage and 5 after each encounter.',
    flavor: 'In, out, in, out.',
    hooks: { onDamageTaken: [{ type: 'heal', value: 1 }], onEncounterEnd: [{ type: 'heal', value: 5 }] },
  },
  {
    id: 'spore-cloud',
    name: 'Spore Cloud',
    rarity: 'uncommon',
    description: 'Deal 3 damage at the start of each turn and +3 on every word.',
    flavor: 'Everywhere, a little.',
    hooks: { onTurnStart: [{ type: 'damageEnemy', value: 3 }], onWordScored: [{ type: 'addFlat', value: 3 }] },
  },
  {
    id: 'ganglion',
    name: 'Ganglion',
    rarity: 'uncommon',
    description: 'Words of 6+ letters deal +20.',
    flavor: 'A knot of nerve. It remembers the long ones.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'minLength', value: 6 }, then: [{ type: 'addFlat', value: 20 }] }] },
  },
  {
    id: 'metamorphosis',
    name: 'Metamorphosis',
    rarity: 'rare',
    description: '+50% damage and heal 15 after each encounter.',
    flavor: 'Come out of it changed.',
    hooks: { onWordScored: [{ type: 'addMult', value: 0.5 }], onEncounterEnd: [{ type: 'heal', value: 15 }] },
  },
  {
    id: 'hydra',
    name: 'Hydra',
    rarity: 'rare',
    description: 'Whenever you take damage, heal 1 and deal 3 back.',
    flavor: 'Cut it. Go on.',
    hooks: { onDamageTaken: [{ type: 'heal', value: 1 }, { type: 'damageEnemy', value: 3 }] },
  },
  {
    id: 'bioluminescence',
    name: 'Bioluminescence',
    rarity: 'rare',
    description: 'Every vowel is worth +2 and J, Q, X and Z are worth +6 each.',
    flavor: 'It shows off. It has earned it.',
    hooks: { onWordScored: [{ type: 'letterBonus', letters: 'aeiou', value: 2 }, { type: 'letterBonus', letters: 'jqxz', value: 6 }] },
  },
  {
    id: 'apoptosis',
    name: 'Apoptosis',
    rarity: 'rare',
    description: '+150% damage, but lose 3 HP at the start of every turn.',
    flavor: 'Burn bright. Burn.',
    hooks: { onWordScored: [{ type: 'addMult', value: 1.5 }], onTurnStart: [{ type: 'damagePlayer', value: 3 }] },
  },
  {
    id: 'quorum',
    name: 'Quorum',
    rarity: 'rare',
    description: 'Every third turn, triple damage.',
    flavor: 'When enough of you agree.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'turnEvery', value: 3 }, then: [{ type: 'addMult', value: 2 }] }] },
  },
  {
    id: 'stem-cell',
    name: 'Stem Cell',
    rarity: 'rare',
    description: 'Heal 40 after each encounter.',
    flavor: 'It can become anything. Mostly, whole.',
    hooks: { onEncounterEnd: [{ type: 'heal', value: 40 }] },
  },
  // Third expansion (Dean, 2026-09-08: "even more"): fourteen regulars, then the mythic tier.
  {
    id: 'cilium-array',
    name: 'Cilium Array',
    rarity: 'common',
    description: 'Words containing L deal +7.',
    flavor: 'Rows and rows of them, all pulling.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'containsLetter', letters: 'l' }, then: [{ type: 'addFlat', value: 7 }] }] },
  },
  {
    id: 'thylakoid',
    name: 'Thylakoid',
    rarity: 'common',
    description: 'Every third turn, heal 6.',
    flavor: 'Stacked and patient.',
    hooks: { onTurnStart: [{ type: 'condition', when: { kind: 'turnEvery', value: 3 }, then: [{ type: 'heal', value: 6 }] }] },
  },
  {
    id: 'pseudopod',
    name: 'Pseudopod',
    rarity: 'common',
    description: 'Words of 3 letters deal +14.',
    flavor: 'A reach, not a limb.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'maxLength', value: 3 }, then: [{ type: 'addFlat', value: 14 }] }] },
  },
  {
    id: 'sheath',
    name: 'Sheath',
    rarity: 'common',
    description: 'On even turns, take 5 less damage from every hit.',
    flavor: 'It opens and closes.',
    hooks: { onDamageTaken: [{ type: 'condition', when: { kind: 'turnEvery', value: 2 }, then: [{ type: 'reduceDamage', value: 5 }] }] },
  },
  {
    id: 'carotenoid',
    name: 'Carotenoid',
    rarity: 'common',
    description: 'C, H and P are worth +3 each.',
    flavor: 'It gives the colour away.',
    hooks: { onWordScored: [{ type: 'letterBonus', letters: 'chp', value: 3 }] },
  },
  {
    id: 'mycelium',
    name: 'Mycelium',
    rarity: 'uncommon',
    description: 'Heal 2 at the start of every turn and deal 2 damage.',
    flavor: 'It is under everything.',
    hooks: { onTurnStart: [{ type: 'heal', value: 2 }, { type: 'damageEnemy', value: 2 }] },
  },
  {
    id: 'barb',
    name: 'Barb',
    rarity: 'uncommon',
    description: 'Whenever you take damage, deal 9 back.',
    flavor: 'It stays in.',
    hooks: { onDamageTaken: [{ type: 'damageEnemy', value: 9 }] },
  },
  {
    id: 'kinetochore',
    name: 'Kinetochore',
    rarity: 'uncommon',
    description: 'Every second turn, +12 damage and heal 2.',
    flavor: 'It pulls the halves apart on cue.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'turnEvery', value: 2 }, then: [{ type: 'addFlat', value: 12 }, { type: 'heal', value: 2 }] }] },
  },
  {
    id: 'nematocyst',
    name: 'Nematocyst',
    rarity: 'uncommon',
    description: 'Words containing T deal +6 and every vowel is worth +1.',
    flavor: 'Coiled, then not.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'containsLetter', letters: 't' }, then: [{ type: 'addFlat', value: 6 }] }, { type: 'letterBonus', letters: 'aeiou', value: 1 }] },
  },
  {
    id: 'endospore',
    name: 'Endospore',
    rarity: 'uncommon',
    description: 'While below 30% HP, take 4 less damage and heal 2 whenever you take damage.',
    flavor: 'It waits out the bad years.',
    hooks: { onDamageTaken: [{ type: 'condition', when: { kind: 'hpBelow', fraction: 0.3 }, then: [{ type: 'reduceDamage', value: 4 }, { type: 'heal', value: 2 }] }] },
  },
  {
    id: 'lateral-line',
    name: 'Lateral Line',
    rarity: 'rare',
    description: 'Words of 6+ letters deal +30 and heal 5.',
    flavor: 'It feels the long ones coming.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'minLength', value: 6 }, then: [{ type: 'addFlat', value: 30 }, { type: 'heal', value: 5 }] }] },
  },
  {
    id: 'nucleolus',
    name: 'Nucleolus',
    rarity: 'rare',
    description: 'Every letter is worth +2.',
    flavor: 'The factory inside the factory.',
    hooks: { onWordScored: [{ type: 'letterBonus', letters: 'abcdefghijklmnopqrstuvwxyz', value: 2 }] },
  },
  {
    id: 'exoskeleton',
    name: 'Exoskeleton',
    rarity: 'rare',
    description: 'Take 8 less damage from every hit, but vowels are drawn 30% less often.',
    flavor: 'Safe, and stiff.',
    hooks: { onDamageTaken: [{ type: 'reduceDamage', value: 8 }], onTileDraw: [{ type: 'vowelWeight', value: 0.7 }] },
  },
  {
    id: 'lysozyme',
    name: 'Lysozyme',
    rarity: 'rare',
    description: 'Deal 10 damage at the start of every turn.',
    flavor: 'It dissolves walls for a living.',
    hooks: { onTurnStart: [{ type: 'damageEnemy', value: 10 }] },
  },
  // Mythic: explicitly overpowered (Dean, 2026-09-08). Weighted 0.35, so a run sees one about half the time.
  {
    id: 'apex-genome',
    name: 'Apex Genome',
    rarity: 'mythic',
    description: 'Triple damage on every word.',
    flavor: 'Everything that ever ate, in one sequence.',
    hooks: { onWordScored: [{ type: 'addMult', value: 2 }] },
  },
  {
    id: 'immortal-line',
    name: 'Immortal Line',
    rarity: 'mythic',
    description: 'Heal to full after each encounter.',
    flavor: 'It has not died yet. It does not plan to.',
    hooks: { onEncounterEnd: [{ type: 'heal', value: 999 }] },
  },
  {
    id: 'plague',
    name: 'Plague',
    rarity: 'mythic',
    description: 'Deal 25 damage to the enemy at the start of every turn.',
    flavor: 'You did not need the word.',
    hooks: { onTurnStart: [{ type: 'damageEnemy', value: 25 }] },
  },
  {
    id: 'tardigrade',
    name: 'Tardigrade',
    rarity: 'mythic',
    description: 'On even turns, take no damage at all.',
    flavor: 'Boil it. Freeze it. Send it to space. Ask it how it feels.',
    hooks: { onDamageTaken: [{ type: 'condition', when: { kind: 'turnEvery', value: 2 }, then: [{ type: 'reduceDamage', value: 999 }] }] },
  },
  {
    id: 'lexicon',
    name: 'Lexicon',
    rarity: 'mythic',
    description: 'Every letter is worth +6.',
    flavor: 'It knows all the words. It is very smug about it.',
    hooks: { onWordScored: [{ type: 'letterBonus', letters: 'abcdefghijklmnopqrstuvwxyz', value: 6 }] },
  },
  {
    id: 'mirror-membrane',
    name: 'Mirror Membrane',
    rarity: 'mythic',
    description: 'Whenever you take damage, deal 20 back and heal 4.',
    flavor: 'Whatever you are, so is it.',
    hooks: { onDamageTaken: [{ type: 'damageEnemy', value: 20 }, { type: 'heal', value: 4 }] },
  },
  {
    id: 'primordial-soup',
    name: 'Primordial Soup',
    rarity: 'mythic',
    description: 'Vowels are drawn three times as often and +100% damage.',
    flavor: 'Where it all started, still bubbling.',
    hooks: { onTileDraw: [{ type: 'vowelWeight', value: 3 }], onWordScored: [{ type: 'addMult', value: 1 }] },
  },
  {
    id: 'hydrothermal-vent',
    name: 'Hydrothermal Vent',
    rarity: 'mythic',
    description: 'Words of 4 letters or fewer deal +50, and heal 5 at the start of every turn.',
    flavor: 'Life started small and hot.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'maxLength', value: 4 }, then: [{ type: 'addFlat', value: 50 }] }], onTurnStart: [{ type: 'heal', value: 5 }] },
  },
  /* ---------- Effects wave, content batch 1 (2026-09-08): forty items on the new verbs ---------- */
  // Commons: one new verb each, plainly.
  { id: 'venom-gland', name: 'Venom Gland', rarity: 'common', description: 'Every word poisons the enemy for 3.', flavor: 'It leaves something behind.', hooks: { onWordScored: [{ type: 'poisonEnemy', value: 3 }] } },
  // Numbing Barb stunned on every 6+ word: 98% wins for the greedy bot (a lock, like Paralytic's first draft). Now poison.
  { id: 'numbing-barb', name: 'Numbing Barb', rarity: 'common', description: 'Words of 6+ letters poison the enemy for 5.', flavor: 'Long enough to reach the nerve.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'minLength', value: 6 }, then: [{ type: 'poisonEnemy', value: 5 }] }] } },
  { id: 'capsule', name: 'Capsule', rarity: 'common', description: 'Gain 4 shield on every word.', flavor: 'A coat that thickens as you talk.', hooks: { onWordScored: [{ type: 'shield', value: 4 }] } },
  { id: 'siphon', name: 'Siphon', rarity: 'common', description: 'Heal 15% of the damage each word deals.', flavor: 'Nothing is wasted.', hooks: { onWordScored: [{ type: 'lifesteal', fraction: 0.15 }] } },
  { id: 'flick', name: 'Flick', rarity: 'common', description: 'After each fight, gain a free shuffle.', flavor: 'A twitch of the tail and the board is new.', hooks: { onEncounterEnd: [{ type: 'freeShuffle', value: 1 }] } },
  { id: 'molt', name: 'Molt', rarity: 'common', description: 'After each word, 2 of your tiles are redrawn.', flavor: 'Shed what you were not using.', hooks: { onWordScored: [{ type: 'redrawTiles', count: 2 }] } },
  { id: 'chemotaxis', name: 'Chemotaxis', rarity: 'common', description: 'S and T are drawn 30% more often, and +3 damage.', flavor: 'It swims toward the letters it likes.', hooks: { onTileDraw: [{ type: 'letterWeight', letters: 'st', value: 1.3 }], onWordScored: [{ type: 'addFlat', value: 3 }] } },
  { id: 'growth-factor', name: 'Growth Factor', rarity: 'common', description: 'When taken: +15 max HP.', flavor: 'More of you, permanently.', hooks: { onPick: [{ type: 'maxHp', value: 15 }] } },
  { id: 'vesicle', name: 'Vesicle', rarity: 'common', description: '+1 damage per organelle you carry.', flavor: 'It counts what you have become.', hooks: { onWordScored: [{ type: 'perUnit', unit: 'item', then: [{ type: 'addFlat', value: 1 }] }] } },
  { id: 'polymerase', name: 'Polymerase', rarity: 'common', description: '+2 damage per letter in the word.', flavor: 'Chain, chain, chain.', hooks: { onWordScored: [{ type: 'perUnit', unit: 'letter', then: [{ type: 'addFlat', value: 2 }] }] } },
  { id: 'capsid', name: 'Capsid', rarity: 'common', description: 'Words starting with C, P or S deal +10.', flavor: 'The shell decides how it opens.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'startsWith', letters: 'cps' }, then: [{ type: 'addFlat', value: 10 }] }] } },
  { id: 'tail-fiber', name: 'Tail Fiber', rarity: 'common', description: 'Words ending in S, D or Y deal +9.', flavor: 'It lands on the last letter.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'endsWith', letters: 'sdy' }, then: [{ type: 'addFlat', value: 9 }] }] } },
  { id: 'diploid', name: 'Diploid', rarity: 'common', description: 'Words with a repeated letter deal +12.', flavor: 'Two copies of everything.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'repeatLetter' }, then: [{ type: 'addFlat', value: 12 }] }] } },
  { id: 'haploid', name: 'Haploid', rarity: 'common', description: 'Words with no repeated letters deal +30%.', flavor: 'One of each, no more.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'uniqueLetters' }, then: [{ type: 'addMult', value: 0.3 }] }] } },
  { id: 'primer', name: 'Primer', rarity: 'common', description: 'On the first turn of each fight, double damage.', flavor: 'It was ready before the fight was.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'firstTurn' }, then: [{ type: 'addMult', value: 1 }] }] } },
  { id: 'coagulant', name: 'Coagulant', rarity: 'common', description: 'Whenever you take damage, gain 3 shield.', flavor: 'The wound closes over.', hooks: { onDamageTaken: [{ type: 'shield', value: 3 }] } },
  { id: 'tannin', name: 'Tannin', rarity: 'common', description: 'Words with 3+ vowels poison the enemy for 4.', flavor: 'Bitter in the open mouth.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'minVowels', value: 3 }, then: [{ type: 'poisonEnemy', value: 4 }] }] } },
  { id: 'scavenger', name: 'Scavenger', rarity: 'common', description: 'At the start of every turn, heal 2 per venomed tile on the grid.', flavor: 'Poison is just food it has not eaten yet.', hooks: { onTurnStart: [{ type: 'perUnit', unit: 'venomedTile', then: [{ type: 'heal', value: 2 }] }] } },
  { id: 'digestive-vacuole', name: 'Digestive Vacuole', rarity: 'common', description: 'While the enemy is below half HP, +12 damage.', flavor: 'It smells the end.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'enemyHpBelow', fraction: 0.5 }, then: [{ type: 'addFlat', value: 12 }] }] } },
  { id: 'pulse', name: 'Pulse', rarity: 'common', description: 'Every second turn, poison the enemy for 2.', flavor: 'Tick. Tick.', hooks: { onTurnStart: [{ type: 'condition', when: { kind: 'turnEvery', value: 2 }, then: [{ type: 'poisonEnemy', value: 2 }] }] } },
  // Uncommons: a verb with a condition, a scaler, or a pair.
  { id: 'keratin', name: 'Keratin', rarity: 'uncommon', description: 'Take 1 less damage from every hit per organelle you carry.', flavor: 'Layers, then more layers.', hooks: { onDamageTaken: [{ type: 'perUnit', unit: 'item', then: [{ type: 'reduceDamage', value: 1 }] }] } },
  // Neurotoxin's stun on every 5+ word was the same lock (98%); the stun is now every second turn.
  { id: 'neurotoxin', name: 'Neurotoxin', rarity: 'uncommon', description: 'Words of 5+ letters poison the enemy for 3; every second turn they also make it skip its next attack.', flavor: 'First the twitch, then the quiet.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'minLength', value: 5 }, then: [{ type: 'poisonEnemy', value: 3 }, { type: 'condition', when: { kind: 'turnEvery', value: 2 }, then: [{ type: 'stun', value: 1 }] }] }] } },
  { id: 'carapace', name: 'Carapace', rarity: 'uncommon', description: 'Gain 12 shield after each fight.', flavor: 'It hardens between meals.', hooks: { onEncounterEnd: [{ type: 'shield', value: 12 }] } },
  { id: 'hemolymph', name: 'Hemolymph', rarity: 'uncommon', description: 'While below half HP, heal 30% of the damage each word deals.', flavor: 'It runs faster when it runs low.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'hpBelow', fraction: 0.5 }, then: [{ type: 'lifesteal', fraction: 0.3 }] }] } },
  { id: 'telomere', name: 'Telomere', rarity: 'uncommon', description: '+5 max HP after each fight.', flavor: 'The ends stop fraying.', hooks: { onEncounterEnd: [{ type: 'maxHp', value: 5 }] } },
  { id: 'kinesin', name: 'Kinesin', rarity: 'uncommon', description: 'When taken: 2 free shuffles.', flavor: 'It walks the rails and moves the cargo.', hooks: { onPick: [{ type: 'freeShuffle', value: 2 }] } },
  { id: 'coccus', name: 'Coccus', rarity: 'uncommon', description: '+1 damage per letter, and +1 more per vowel.', flavor: 'Round, and rounder.', hooks: { onWordScored: [{ type: 'perUnit', unit: 'letter', then: [{ type: 'addFlat', value: 1 }] }, { type: 'perUnit', unit: 'vowel', then: [{ type: 'addFlat', value: 1 }] }] } },
  { id: 'sporangium', name: 'Sporangium', rarity: 'uncommon', description: 'Every third turn, 4 tiles are redrawn and words deal +20.', flavor: 'It bursts on schedule.', hooks: { onTurnStart: [{ type: 'condition', when: { kind: 'turnEvery', value: 3 }, then: [{ type: 'redrawTiles', count: 4 }] }], onWordScored: [{ type: 'condition', when: { kind: 'turnEvery', value: 3 }, then: [{ type: 'addFlat', value: 20 }] }] } },
  { id: 'ink-sac', name: 'Ink Sac', rarity: 'uncommon', description: 'Words starting with a vowel deal +60%.', flavor: 'It opens with a cloud.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'startsWith', letters: 'aeiou' }, then: [{ type: 'addMult', value: 0.6 }] }] } },
  { id: 'amylase', name: 'Amylase', rarity: 'uncommon', description: 'E, A and R are drawn 60% more often, and +4 damage.', flavor: 'It breaks the common things down fastest.', hooks: { onTileDraw: [{ type: 'letterWeight', letters: 'ear', value: 1.6 }], onWordScored: [{ type: 'addFlat', value: 4 }] } },
  { id: 'cnidocyte', name: 'Cnidocyte', rarity: 'uncommon', description: 'Words containing J, K, Q, X or Z make the enemy skip its next attack.', flavor: 'A harpoon on a hair trigger.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'containsLetter', letters: 'jkqxz' }, then: [{ type: 'stun', value: 1 }] }] } },
  { id: 'antitoxin', name: 'Antitoxin', rarity: 'uncommon', description: 'Every second turn, gain 6 shield.', flavor: 'It answers before the question.', hooks: { onTurnStart: [{ type: 'condition', when: { kind: 'turnEvery', value: 2 }, then: [{ type: 'shield', value: 6 }] }] } },
  // Rares: the scalers and the trades.
  { id: 'opsonin', name: 'Opsonin', rarity: 'rare', description: 'Every word poisons the enemy for 1 per organelle you carry.', flavor: 'It marks the target for everyone else.', hooks: { onWordScored: [{ type: 'perUnit', unit: 'item', then: [{ type: 'poisonEnemy', value: 1 }] }] } },
  { id: 'cortex', name: 'Cortex', rarity: 'rare', description: '+10% damage per organelle you carry.', flavor: 'Structure is strength.', hooks: { onWordScored: [{ type: 'perUnit', unit: 'item', then: [{ type: 'addMult', value: 0.1 }] }] } },
  // Paralytic's first draft stunned on every word: a permanent lock against every-turn attackers,
  // 98% wins for the mediocre bot at 1500 runs. Now every second turn, and it still costs damage.
  { id: 'paralytic', name: 'Paralytic', rarity: 'rare', description: 'Every second turn, your word makes the enemy skip its next attack; -30% damage.', flavor: 'Slow, and slower.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'turnEvery', value: 2 }, then: [{ type: 'stun', value: 1 }] }, { type: 'addMult', value: -0.3 }] } },
  { id: 'zooxanthellae', name: 'Zooxanthellae', rarity: 'rare', description: 'Heal 25% of the damage each word deals.', flavor: 'A tenant that pays in sunlight.', hooks: { onWordScored: [{ type: 'lifesteal', fraction: 0.25 }] } },
  { id: 'reflex-arc', name: 'Reflex Arc', rarity: 'rare', description: 'Whenever you take damage, deal 6 back and the enemy skips its next attack.', flavor: 'It answers before you feel it.', hooks: { onDamageTaken: [{ type: 'damageEnemy', value: 6 }, { type: 'stun', value: 1 }] } },
  { id: 'blastula', name: 'Blastula', rarity: 'rare', description: 'When taken: +30 max HP. Heal 10 after each fight.', flavor: 'A hollow ball, about to become everything.', hooks: { onPick: [{ type: 'maxHp', value: 30 }], onEncounterEnd: [{ type: 'heal', value: 10 }] } },
  { id: 'chrysalis', name: 'Chrysalis', rarity: 'rare', description: 'At the start of every turn, gain 4 shield.', flavor: 'Wrapped, and working.', hooks: { onTurnStart: [{ type: 'shield', value: 4 }] } },
  // Mythic: explicitly powered.
  { id: 'ouroboros', name: 'Ouroboros', rarity: 'mythic', description: 'Every word poisons the enemy for 12 and heals 30% of its damage.', flavor: 'It eats, and it is eaten, and it is fine.', hooks: { onWordScored: [{ type: 'poisonEnemy', value: 12 }, { type: 'lifesteal', fraction: 0.3 }] } },
  /* ---------- Effects wave, content batch 2 (2026-09-08): forty-five items in synergy pairs ---------- */
  // Venom pair: make your own venom, then feed on it (Scavenger, Antivenin, Venom Loop, Venom Crown).
  { id: 'venom-reservoir', name: 'Venom Reservoir', rarity: 'common', description: 'At the start of every turn one clean tile turns venomous, and words deal +12.', flavor: 'It keeps the poison close. Too close.', hooks: { onTurnStart: [{ type: 'venomTiles', count: 1, value: 1 }], onWordScored: [{ type: 'addFlat', value: 12 }] } },
  { id: 'antivenin', name: 'Antivenin', rarity: 'common', description: 'Words deal +4 per venomed tile on the grid.', flavor: 'What does not kill you, it sells.', hooks: { onWordScored: [{ type: 'perUnit', unit: 'venomedTile', then: [{ type: 'addFlat', value: 4 }] }] } },
  { id: 'lockpick', name: 'Lockpick', rarity: 'common', description: 'Words deal +6 per locked tile on the grid.', flavor: 'A closed door is a hint.', hooks: { onWordScored: [{ type: 'perUnit', unit: 'lockedTile', then: [{ type: 'addFlat', value: 6 }] }] } },
  // Missing-HP pair: the lower you are, the harder you hit and the less you take (Crust, Adrenaline, Frenzy).
  { id: 'crust', name: 'Crust', rarity: 'common', description: 'Take 1 less damage from every hit per 10% HP you are missing.', flavor: 'Scar tissue, layered.', hooks: { onDamageTaken: [{ type: 'perUnit', unit: 'missingTenth', then: [{ type: 'reduceDamage', value: 1 }] }] } },
  { id: 'adrenaline', name: 'Adrenaline', rarity: 'common', description: '+8% damage per 10% HP you are missing.', flavor: 'The edge is where it works.', hooks: { onWordScored: [{ type: 'perUnit', unit: 'missingTenth', then: [{ type: 'addMult', value: 0.08 }] }] } },
  // Cadence pair: the fight gets louder the longer it runs (Circadian Clock, Overclock, Hourglass).
  { id: 'circadian-clock', name: 'Circadian Clock', rarity: 'common', description: '+2 damage per turn of the fight.', flavor: 'It counts, and it does not stop.', hooks: { onWordScored: [{ type: 'perUnit', unit: 'turn', then: [{ type: 'addFlat', value: 2 }] }] } },
  // Letter-shape pair: consonants or vowels, pick a side (Consonant Coat, Vowel Sac, Gill, Deep Breath).
  { id: 'consonant-coat', name: 'Consonant Coat', rarity: 'common', description: '+2 damage per consonant in the word.', flavor: 'Hard sounds, hard shell.', hooks: { onWordScored: [{ type: 'perUnit', unit: 'consonant', then: [{ type: 'addFlat', value: 2 }] }] } },
  { id: 'vowel-sac', name: 'Vowel Sac', rarity: 'common', description: '+4 damage per vowel in the word.', flavor: 'It sings, in its way.', hooks: { onWordScored: [{ type: 'perUnit', unit: 'vowel', then: [{ type: 'addFlat', value: 4 }] }] } },
  { id: 'rare-earth', name: 'Rare Earth', rarity: 'common', description: 'Words containing J, K, Q, X or Z gain 6 shield.', flavor: 'Heavy elements, heavy skin.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'containsLetter', letters: 'jkqxz' }, then: [{ type: 'shield', value: 6 }] }] } },
  { id: 'spit', name: 'Spit', rarity: 'common', description: 'Words ending in T poison the enemy for 3.', flavor: 'Punctuation with a payload.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'endsWith', letters: 't' }, then: [{ type: 'poisonEnemy', value: 3 }] }] } },
  { id: 'opener', name: 'Opener', rarity: 'common', description: 'Words starting with a vowel poison the enemy for 2 and deal +4.', flavor: 'It gets the first word in.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'startsWith', letters: 'aeiou' }, then: [{ type: 'poisonEnemy', value: 2 }, { type: 'addFlat', value: 4 }] }] } },
  { id: 'sprint', name: 'Sprint', rarity: 'common', description: 'On the first turn of each fight, gain 10 shield.', flavor: 'Fast out of the gate, then tired.', hooks: { onTurnStart: [{ type: 'condition', when: { kind: 'firstTurn' }, then: [{ type: 'shield', value: 10 }] }] } },
  { id: 'patience', name: 'Patience', rarity: 'common', description: 'Every fourth turn, 6 tiles are redrawn and you heal 6.', flavor: 'Wait for it.', hooks: { onTurnStart: [{ type: 'condition', when: { kind: 'turnEvery', value: 4 }, then: [{ type: 'redrawTiles', count: 6 }, { type: 'heal', value: 6 }] }] } },
  { id: 'relay', name: 'Relay', rarity: 'common', description: 'Four-letter words deal +16.', flavor: 'Short legs, fast hands.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'minLength', value: 4 }, then: [{ type: 'condition', when: { kind: 'maxLength', value: 4 }, then: [{ type: 'addFlat', value: 16 }] }] }] } },
  { id: 'gill', name: 'Gill', rarity: 'common', description: 'Words with 2+ vowels heal 2.', flavor: 'It breathes through the open sounds.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'minVowels', value: 2 }, then: [{ type: 'heal', value: 2 }] }] } },
  { id: 'mantle', name: 'Mantle', rarity: 'common', description: 'Gain 2 shield at the start of every turn.', flavor: 'A slow, steady coat.', hooks: { onTurnStart: [{ type: 'shield', value: 2 }] } },
  { id: 'twin', name: 'Twin', rarity: 'common', description: 'Words with a repeated letter poison the enemy for 3.', flavor: 'It says everything twice.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'repeatLetter' }, then: [{ type: 'poisonEnemy', value: 3 }] }] } },
  { id: 'singleton', name: 'Singleton', rarity: 'common', description: 'Words with no repeated letters deal +2 per letter.', flavor: 'Every piece unique, every piece counted.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'uniqueLetters' }, then: [{ type: 'perUnit', unit: 'letter', then: [{ type: 'addFlat', value: 2 }] }] }] } },
  { id: 'leftover', name: 'Leftover', rarity: 'common', description: 'After each fight, heal 2 per organelle you carry.', flavor: 'The meal after the meal.', hooks: { onEncounterEnd: [{ type: 'perUnit', unit: 'item', then: [{ type: 'heal', value: 2 }] }] } },
  { id: 'bait', name: 'Bait', rarity: 'common', description: 'E and S are drawn 30% more often, and words deal +3.', flavor: 'The common letters come when called.', hooks: { onTileDraw: [{ type: 'letterWeight', letters: 'es', value: 1.3 }], onWordScored: [{ type: 'addFlat', value: 3 }] } },
  { id: 'rasp', name: 'Rasp', rarity: 'common', description: 'R, S and T are worth +2 each, and words ending in S deal +4.', flavor: 'Rough on the way out.', hooks: { onWordScored: [{ type: 'letterBonus', letters: 'rst', value: 2 }, { type: 'condition', when: { kind: 'endsWith', letters: 's' }, then: [{ type: 'addFlat', value: 4 }] }] } },
  { id: 'jolt', name: 'Jolt', rarity: 'common', description: 'Whenever you take damage, poison the enemy for 3.', flavor: 'Touch it and regret it.', hooks: { onDamageTaken: [{ type: 'poisonEnemy', value: 3 }] } },
  // Uncommons.
  { id: 'pheromone', name: 'Pheromone', rarity: 'uncommon', description: 'Words of 5+ letters deal +3 per organelle you carry.', flavor: 'The colony answers a long call.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'minLength', value: 5 }, then: [{ type: 'perUnit', unit: 'item', then: [{ type: 'addFlat', value: 3 }] }] }] } },
  { id: 'hardshell', name: 'Hardshell', rarity: 'uncommon', description: 'Take 3 less damage from every hit, and gain 2 shield whenever you take damage.', flavor: 'It learns from every knock.', hooks: { onDamageTaken: [{ type: 'reduceDamage', value: 3 }, { type: 'shield', value: 2 }] } },
  { id: 'venom-loop', name: 'Venom Loop', rarity: 'uncommon', description: 'At the start of every turn one clean tile turns venomous, and you heal 4 per venomed tile.', flavor: 'It drinks its own bite.', hooks: { onTurnStart: [{ type: 'venomTiles', count: 1, value: 1 }, { type: 'perUnit', unit: 'venomedTile', then: [{ type: 'heal', value: 4 }] }] } },
  { id: 'metronome', name: 'Metronome', rarity: 'uncommon', description: 'Every second turn, +50% damage.', flavor: 'Tick, TOCK.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'turnEvery', value: 2 }, then: [{ type: 'addMult', value: 0.5 }] }] } },
  { id: 'reaper', name: 'Reaper', rarity: 'uncommon', description: 'While the enemy is below 30% HP, double damage.', flavor: 'It only shows up for the ending.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'enemyHpBelow', fraction: 0.3 }, then: [{ type: 'addMult', value: 1 }] }] } },
  { id: 'overclock', name: 'Overclock', rarity: 'uncommon', description: '+4% damage per turn of the fight.', flavor: 'Warmer every turn.', hooks: { onWordScored: [{ type: 'perUnit', unit: 'turn', then: [{ type: 'addMult', value: 0.04 }] }] } },
  { id: 'deep-breath', name: 'Deep Breath', rarity: 'uncommon', description: 'Words with 3+ vowels heal 8 and gain 4 shield.', flavor: 'In through the O, out through the U.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'minVowels', value: 3 }, then: [{ type: 'heal', value: 8 }, { type: 'shield', value: 4 }] }] } },
  { id: 'chelator', name: 'Chelator', rarity: 'uncommon', description: 'Words of 7+ letters redraw the rest of the grid.', flavor: 'It grabs everything and lets go at once.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'minLength', value: 7 }, then: [{ type: 'redrawTiles', count: 16 }] }] } },
  { id: 'lantern', name: 'Lantern', rarity: 'uncommon', description: 'Every third turn, the enemy skips its next attack.', flavor: 'Light, then a flinch.', hooks: { onTurnStart: [{ type: 'condition', when: { kind: 'turnEvery', value: 3 }, then: [{ type: 'stun', value: 1 }] }] } },
  { id: 'buffer', name: 'Buffer', rarity: 'uncommon', description: 'When taken: 20 shield. After each fight: 6 shield.', flavor: 'It keeps the pH, and the peace.', hooks: { onPick: [{ type: 'shield', value: 20 }], onEncounterEnd: [{ type: 'shield', value: 6 }] } },
  { id: 'eater', name: 'Eater', rarity: 'uncommon', description: 'Heal 15% of the damage each word deals, and +2 damage per vowel.', flavor: 'Chews with its mouth open.', hooks: { onWordScored: [{ type: 'lifesteal', fraction: 0.15 }, { type: 'perUnit', unit: 'vowel', then: [{ type: 'addFlat', value: 2 }] }] } },
  { id: 'frenzy', name: 'Frenzy', rarity: 'uncommon', description: 'While below half HP, words poison the enemy for 5 and deal +10.', flavor: 'Cornered is a strategy.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'hpBelow', fraction: 0.5 }, then: [{ type: 'poisonEnemy', value: 5 }, { type: 'addFlat', value: 10 }] }] } },
  { id: 'tuning-fork', name: 'Tuning Fork', rarity: 'uncommon', description: 'L and N are drawn twice as often and are worth +3 each.', flavor: 'Two notes, held.', hooks: { onTileDraw: [{ type: 'letterWeight', letters: 'ln', value: 2 }], onWordScored: [{ type: 'letterBonus', letters: 'ln', value: 3 }] } },
  // Rares.
  { id: 'ambush', name: 'Ambush', rarity: 'rare', description: 'On the first turn of each fight, triple damage and the enemy skips its next attack.', flavor: 'It was in the water the whole time.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'firstTurn' }, then: [{ type: 'addMult', value: 2 }, { type: 'stun', value: 1 }] }] } },
  { id: 'hive', name: 'Hive', rarity: 'rare', description: '+2 damage per organelle you carry, and heal 1 per organelle after each fight.', flavor: 'Many rooms, one mind.', hooks: { onWordScored: [{ type: 'perUnit', unit: 'item', then: [{ type: 'addFlat', value: 2 }] }], onEncounterEnd: [{ type: 'perUnit', unit: 'item', then: [{ type: 'heal', value: 1 }] }] } },
  { id: 'bastion', name: 'Bastion', rarity: 'rare', description: 'Gain 5 shield at the start of every turn, and take 2 less damage from every hit.', flavor: 'It does not move. Things move around it.', hooks: { onTurnStart: [{ type: 'shield', value: 5 }], onDamageTaken: [{ type: 'reduceDamage', value: 2 }] } },
  { id: 'venom-crown', name: 'Venom Crown', rarity: 'rare', description: 'Words deal +9 per venomed tile on the grid, and each turn one clean tile turns venomous.', flavor: 'Wear the danger where everyone can see it.', hooks: { onWordScored: [{ type: 'perUnit', unit: 'venomedTile', then: [{ type: 'addFlat', value: 9 }] }], onTurnStart: [{ type: 'venomTiles', count: 1, value: 1 }] } },
  { id: 'hourglass', name: 'Hourglass', rarity: 'rare', description: '+5 damage per turn of the fight, and every fifth turn 8 tiles are redrawn.', flavor: 'Sand, then more sand.', hooks: { onWordScored: [{ type: 'perUnit', unit: 'turn', then: [{ type: 'addFlat', value: 5 }] }], onTurnStart: [{ type: 'condition', when: { kind: 'turnEvery', value: 5 }, then: [{ type: 'redrawTiles', count: 8 }] }] } },
  { id: 'leviathan', name: 'Leviathan', rarity: 'rare', description: 'Words of 8+ letters deal +80 and the enemy skips its next two attacks.', flavor: 'Something that size does not need to hurry.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'minLength', value: 8 }, then: [{ type: 'addFlat', value: 80 }, { type: 'stun', value: 2 }] }] } },
  { id: 'phage', name: 'Phage', rarity: 'rare', description: 'Every word poisons the enemy for 6 and heals 15% of its damage.', flavor: 'It lands, it injects, it waits.', hooks: { onWordScored: [{ type: 'poisonEnemy', value: 6 }, { type: 'lifesteal', fraction: 0.15 }] } },
  { id: 'osmoregulator', name: 'Osmoregulator', rarity: 'rare', description: 'When taken: +25 max HP. Heal 15% of the damage each word deals.', flavor: 'Balance, kept by force.', hooks: { onPick: [{ type: 'maxHp', value: 25 }], onWordScored: [{ type: 'lifesteal', fraction: 0.15 }] } },
  // Mythics: explicitly powered.
  { id: 'singularity', name: 'Singularity', rarity: 'mythic', description: '+1 damage per letter in the word, per organelle you carry.', flavor: 'Everything you are, in every word.', hooks: { onWordScored: [{ type: 'perUnit', unit: 'item', then: [{ type: 'perUnit', unit: 'letter', then: [{ type: 'addFlat', value: 1 }] }] }] } },
  { id: 'eternal-return', name: 'Eternal Return', rarity: 'mythic', description: 'Every second turn the enemy skips its attack, and you heal 10 at the start of every turn.', flavor: 'It has done this before. It will do it again.', hooks: { onTurnStart: [{ type: 'heal', value: 10 }, { type: 'condition', when: { kind: 'turnEvery', value: 2 }, then: [{ type: 'stun', value: 1 }] }] } },
  /* ---------- Effects wave, content batch 3 (2026-09-08): the last forty-three, to 200 ---------- */
  // Commons.
  { id: 'flagellin', name: 'Flagellin', rarity: 'common', description: '+8 damage per J, K, Q, X or Z in the word.', flavor: 'The rare parts are the moving parts.', hooks: { onWordScored: [{ type: 'perUnit', unit: 'rareLetter', then: [{ type: 'addFlat', value: 8 }] }] } },
  { id: 'mucilage', name: 'Mucilage', rarity: 'common', description: 'Whenever you take damage, heal 2 and gain 1 shield.', flavor: 'Sticky, and stickier.', hooks: { onDamageTaken: [{ type: 'heal', value: 2 }, { type: 'shield', value: 1 }] } },
  { id: 'kelp', name: 'Kelp', rarity: 'common', description: 'Words containing E deal +5.', flavor: 'Everywhere, and useful.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'containsLetter', letters: 'e' }, then: [{ type: 'addFlat', value: 5 }] }] } },
  { id: 'thorn', name: 'Thorn', rarity: 'common', description: 'Whenever you take damage, deal 4 back and poison the enemy for 1.', flavor: 'Touch it, bleed a little, keep bleeding.', hooks: { onDamageTaken: [{ type: 'damageEnemy', value: 4 }, { type: 'poisonEnemy', value: 1 }] } },
  { id: 'ballast', name: 'Ballast', rarity: 'common', description: '+6 damage, but vowels are drawn 20% less often.', flavor: 'Heavy, and it shows.', hooks: { onWordScored: [{ type: 'addFlat', value: 6 }], onTileDraw: [{ type: 'vowelWeight', value: 0.8 }] } },
  { id: 'filament', name: 'Filament', rarity: 'common', description: 'Words of 5+ letters gain 5 shield.', flavor: 'Spun long, worn thin.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'minLength', value: 5 }, then: [{ type: 'shield', value: 5 }] }] } },
  { id: 'echo', name: 'Echo', rarity: 'common', description: 'Words ending in E deal +6.', flavor: 'It trails off, and lands.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'endsWith', letters: 'e' }, then: [{ type: 'addFlat', value: 6 }] }] } },
  { id: 'gullet', name: 'Gullet', rarity: 'common', description: 'Words of 6+ letters heal 1 per letter.', flavor: 'A big meal goes down slowly.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'minLength', value: 6 }, then: [{ type: 'perUnit', unit: 'letter', then: [{ type: 'heal', value: 1 }] }] }] } },
  { id: 'pebble', name: 'Pebble', rarity: 'common', description: 'Take 1 less damage from every hit, and +3 damage.', flavor: 'Small. Dense. Thrown.', hooks: { onDamageTaken: [{ type: 'reduceDamage', value: 1 }], onWordScored: [{ type: 'addFlat', value: 3 }] } },
  { id: 'lichen', name: 'Lichen', rarity: 'common', description: 'Heal 1 per vowel in the word.', flavor: 'Two things living as one, slowly.', hooks: { onWordScored: [{ type: 'perUnit', unit: 'vowel', then: [{ type: 'heal', value: 1 }] }] } },
  { id: 'spiracle', name: 'Spiracle', rarity: 'common', description: 'Every third turn, heal 6 and gain 3 shield.', flavor: 'It breathes on its own schedule.', hooks: { onTurnStart: [{ type: 'condition', when: { kind: 'turnEvery', value: 3 }, then: [{ type: 'heal', value: 6 }, { type: 'shield', value: 3 }] }] } },
  { id: 'tremor', name: 'Tremor', rarity: 'common', description: 'Three-letter words deal +10 and redraw 4 tiles.', flavor: 'A small word shakes the board.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'maxLength', value: 3 }, then: [{ type: 'addFlat', value: 10 }, { type: 'redrawTiles', count: 4 }] }] } },
  { id: 'sap', name: 'Sap', rarity: 'common', description: 'Words with 2+ vowels poison the enemy for 2.', flavor: 'Sweet going in.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'minVowels', value: 2 }, then: [{ type: 'poisonEnemy', value: 2 }] }] } },
  { id: 'bristle', name: 'Bristle', rarity: 'common', description: 'Words starting with a consonant deal +5.', flavor: 'Hard on the way in.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'startsWith', letters: 'bcdfghjklmnpqrstvwxyz' }, then: [{ type: 'addFlat', value: 5 }] }] } },
  { id: 'cocoon', name: 'Cocoon', rarity: 'common', description: 'When taken: 15 shield and +5 max HP.', flavor: 'Wrapped once, changed for good.', hooks: { onPick: [{ type: 'shield', value: 15 }, { type: 'maxHp', value: 5 }] } },
  { id: 'nerve-net', name: 'Nerve Net', rarity: 'common', description: '+2% damage per organelle you carry.', flavor: 'Everything talks to everything.', hooks: { onWordScored: [{ type: 'perUnit', unit: 'item', then: [{ type: 'addMult', value: 0.02 }] }] } },
  { id: 'tide', name: 'Tide', rarity: 'common', description: 'Every second turn, 3 tiles are redrawn.', flavor: 'In, out, new sand.', hooks: { onTurnStart: [{ type: 'condition', when: { kind: 'turnEvery', value: 2 }, then: [{ type: 'redrawTiles', count: 3 }] }] } },
  { id: 'seed', name: 'Seed', rarity: 'common', description: '+3 max HP after each fight.', flavor: 'Small now.', hooks: { onEncounterEnd: [{ type: 'maxHp', value: 3 }] } },
  { id: 'talon', name: 'Talon', rarity: 'common', description: 'Words of 7+ letters deal +25.', flavor: 'It only closes on something big.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'minLength', value: 7 }, then: [{ type: 'addFlat', value: 25 }] }] } },
  { id: 'grit', name: 'Grit', rarity: 'common', description: 'While below 30% HP, gain 6 shield at the start of every turn.', flavor: 'The last third is the hard third.', hooks: { onTurnStart: [{ type: 'condition', when: { kind: 'hpBelow', fraction: 0.3 }, then: [{ type: 'shield', value: 6 }] }] } },
  { id: 'burrow', name: 'Burrow', rarity: 'common', description: 'Every fifth turn, the enemy skips its next attack.', flavor: 'Gone, briefly.', hooks: { onTurnStart: [{ type: 'condition', when: { kind: 'turnEvery', value: 5 }, then: [{ type: 'stun', value: 1 }] }] } },
  { id: 'glow', name: 'Glow', rarity: 'common', description: 'Words with no repeated letters heal 3.', flavor: 'Clean light from clean parts.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'uniqueLetters' }, then: [{ type: 'heal', value: 3 }] }] } },
  // Uncommons.
  { id: 'venom-fang', name: 'Venom Fang', rarity: 'uncommon', description: 'Words deal +6 per venomed tile on the grid, and you heal 1 per venomed tile at the start of every turn.', flavor: 'It bites what bites it.', hooks: { onWordScored: [{ type: 'perUnit', unit: 'venomedTile', then: [{ type: 'addFlat', value: 6 }] }], onTurnStart: [{ type: 'perUnit', unit: 'venomedTile', then: [{ type: 'heal', value: 1 }] }] } },
  { id: 'warden', name: 'Warden', rarity: 'uncommon', description: 'Words deal +8 per locked tile, and you take 2 less damage per locked tile.', flavor: 'It likes a closed room.', hooks: { onWordScored: [{ type: 'perUnit', unit: 'lockedTile', then: [{ type: 'addFlat', value: 8 }] }], onDamageTaken: [{ type: 'perUnit', unit: 'lockedTile', then: [{ type: 'reduceDamage', value: 2 }] }] } },
  { id: 'lodestone', name: 'Lodestone', rarity: 'uncommon', description: 'J, K, Q, X and Z are drawn 50% more often and are worth +4 each.', flavor: 'The heavy letters come to it.', hooks: { onTileDraw: [{ type: 'letterWeight', letters: 'jkqxz', value: 1.5 }], onWordScored: [{ type: 'letterBonus', letters: 'jkqxz', value: 4 }] } },
  { id: 'pressure', name: 'Pressure', rarity: 'uncommon', description: '+2 damage per 10% HP you are missing.', flavor: 'Squeezed, it pushes back.', hooks: { onWordScored: [{ type: 'perUnit', unit: 'missingTenth', then: [{ type: 'addFlat', value: 2 }] }] } },
  { id: 'anchor', name: 'Anchor', rarity: 'uncommon', description: 'Words of 4 letters or fewer deal +6 and gain 8 shield.', flavor: 'Short chain, firm hold.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'maxLength', value: 4 }, then: [{ type: 'addFlat', value: 6 }, { type: 'shield', value: 8 }] }] } },
  { id: 'syncopation', name: 'Syncopation', rarity: 'uncommon', description: 'Every second turn, words poison the enemy for 6.', flavor: 'The off-beat is the one that lands.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'turnEvery', value: 2 }, then: [{ type: 'poisonEnemy', value: 6 }] }] } },
  { id: 'long-arm', name: 'Long Arm', rarity: 'uncommon', description: 'Words of 6+ letters heal 6 and gain 4 shield.', flavor: 'Reach, and be reached less.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'minLength', value: 6 }, then: [{ type: 'heal', value: 6 }, { type: 'shield', value: 4 }] }] } },
  { id: 'slipstream', name: 'Slipstream', rarity: 'uncommon', description: 'After each fight, gain 2 free shuffles.', flavor: 'Ride the wake into the next one.', hooks: { onEncounterEnd: [{ type: 'freeShuffle', value: 2 }] } },
  { id: 'ricochet', name: 'Ricochet', rarity: 'uncommon', description: 'Whenever you take damage, deal 5 back and gain 3 shield.', flavor: 'It comes back at an angle.', hooks: { onDamageTaken: [{ type: 'damageEnemy', value: 5 }, { type: 'shield', value: 3 }] } },
  { id: 'pulsar', name: 'Pulsar', rarity: 'uncommon', description: 'On the first turn of each fight, poison the enemy for 10 and deal +20.', flavor: 'One flash, then the slow burn.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'firstTurn' }, then: [{ type: 'poisonEnemy', value: 10 }, { type: 'addFlat', value: 20 }] }] } },
  { id: 'mimic', name: 'Mimic', rarity: 'uncommon', description: '+2 damage per organelle you carry and +1 per letter in the word.', flavor: 'A little of everything you have met.', hooks: { onWordScored: [{ type: 'perUnit', unit: 'item', then: [{ type: 'addFlat', value: 2 }] }, { type: 'perUnit', unit: 'letter', then: [{ type: 'addFlat', value: 1 }] }] } },
  { id: 'oracle', name: 'Oracle', rarity: 'uncommon', description: 'Words starting with a vowel heal 5 and deal +8.', flavor: 'It speaks first and knows why.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'startsWith', letters: 'aeiou' }, then: [{ type: 'heal', value: 5 }, { type: 'addFlat', value: 8 }] }] } },
  // Rares.
  { id: 'colossus', name: 'Colossus', rarity: 'rare', description: 'When taken: +40 max HP. Take 3 less damage from every hit.', flavor: 'It does not dodge. It does not need to.', hooks: { onPick: [{ type: 'maxHp', value: 40 }], onDamageTaken: [{ type: 'reduceDamage', value: 3 }] } },
  { id: 'venom-heart', name: 'Venom Heart', rarity: 'rare', description: 'Each turn two clean tiles turn venomous; words deal +8 per venomed tile, and you heal 2 per venomed tile at the start of every turn.', flavor: 'It pumps what would kill anything else.', hooks: { onTurnStart: [{ type: 'venomTiles', count: 2, value: 1 }, { type: 'perUnit', unit: 'venomedTile', then: [{ type: 'heal', value: 2 }] }], onWordScored: [{ type: 'perUnit', unit: 'venomedTile', then: [{ type: 'addFlat', value: 8 }] }] } },
  { id: 'clockwork', name: 'Clockwork', rarity: 'rare', description: 'Every second turn, +40% damage and the enemy skips its next attack.', flavor: 'Wound tight, it strikes on the beat.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'turnEvery', value: 2 }, then: [{ type: 'addMult', value: 0.4 }, { type: 'stun', value: 1 }] }] } },
  { id: 'glutton', name: 'Glutton', rarity: 'rare', description: 'Heal 15% of the damage each word deals, and +2 damage per organelle you carry.', flavor: 'It eats, and it grows, and it eats.', hooks: { onWordScored: [{ type: 'lifesteal', fraction: 0.15 }, { type: 'perUnit', unit: 'item', then: [{ type: 'addFlat', value: 2 }] }] } },
  { id: 'scalpel', name: 'Scalpel', rarity: 'rare', description: 'While the enemy is below half HP, +60% damage and words poison it for 4.', flavor: 'Precise, once the opening shows.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'enemyHpBelow', fraction: 0.5 }, then: [{ type: 'addMult', value: 0.6 }, { type: 'poisonEnemy', value: 4 }] }] } },
  { id: 'wellspring', name: 'Wellspring', rarity: 'rare', description: 'Heal 6 at the start of every turn, but -20% damage.', flavor: 'It never runs dry, and it never hurries.', hooks: { onTurnStart: [{ type: 'heal', value: 6 }], onWordScored: [{ type: 'addMult', value: -0.2 }] } },
  { id: 'tectonic', name: 'Tectonic', rarity: 'rare', description: 'Words of 7+ letters deal +40, poison the enemy for 6 and redraw the rest of the grid.', flavor: 'The ground moves when it speaks.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'minLength', value: 7 }, then: [{ type: 'addFlat', value: 40 }, { type: 'poisonEnemy', value: 6 }, { type: 'redrawTiles', count: 16 }] }] } },
  { id: 'keystone', name: 'Keystone', rarity: 'rare', description: 'Words with no repeated letters deal +5 per letter.', flavor: 'Every piece holds the others up.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'uniqueLetters' }, then: [{ type: 'perUnit', unit: 'letter', then: [{ type: 'addFlat', value: 5 }] }] }] } },
  // Mythic.
  { id: 'protocell', name: 'Protocell', rarity: 'mythic', description: 'Every word heals 40% of its damage, gains 10 shield and poisons the enemy for 8.', flavor: 'The first one. Everything since is a footnote.', hooks: { onWordScored: [{ type: 'lifesteal', fraction: 0.4 }, { type: 'shield', value: 10 }, { type: 'poisonEnemy', value: 8 }] } },
  // Curses (variety wave step 6). Each carries `curse: true` and self-harm hooks from the existing
  // verbs; they never appear as a normal boon (drawOffer filters them) and are drawn only as the
  // cost attached to a boon in a cursed offer. The rarity is cosmetic here (curses are drawn
  // uniformly, not by weight); it only tints the compendium entry.
  { id: 'curse-dull', name: 'Blunting', rarity: 'common', curse: true, description: 'Every word deals 5 less damage.', flavor: 'The edge goes first, then the will.', hooks: { onWordScored: [{ type: 'addFlat', value: -5 }] } },
  { id: 'curse-weak', name: 'Enervation', rarity: 'common', curse: true, description: 'Your words deal 25% less damage.', flavor: 'The strength is there. It just will not come.', hooks: { onWordScored: [{ type: 'addMult', value: -0.25 }] } },
  { id: 'curse-lumber', name: 'Lumbering', rarity: 'uncommon', curse: true, description: 'Words of 6 or more letters deal half damage.', flavor: 'The long ones drag on the floor.', hooks: { onWordScored: [{ type: 'condition', when: { kind: 'minLength', value: 6 }, then: [{ type: 'addMult', value: -0.5 }] }] } },
  { id: 'curse-thin-skin', name: 'Thin Skin', rarity: 'common', curse: true, description: 'Basic enemy attacks hit for 2 more. Specials and venom are unaffected.', flavor: 'Everything gets a little closer to the quick.', hooks: { onDamageTaken: [{ type: 'reduceDamage', value: -2 }] } },
  { id: 'curse-bleed', name: 'Hemorrhage', rarity: 'uncommon', curse: true, description: 'Lose 1 HP at the start of every turn.', flavor: 'A slow leak you cannot find the source of.', hooks: { onTurnStart: [{ type: 'damagePlayer', value: 1 }] } },
  { id: 'curse-frail', name: 'Atrophy', rarity: 'common', curse: true, description: 'Lose 15 max HP when taken.', flavor: 'Less of you to carry the rest.', hooks: { onPick: [{ type: 'maxHp', value: -15 }] } },
  { id: 'curse-drought', name: 'Drought', rarity: 'common', curse: true, description: 'Vowels are drawn 40% less often.', flavor: 'The wells that make words go dry.', hooks: { onTileDraw: [{ type: 'vowelWeight', value: 0.6 }] } },
  { id: 'curse-shackle', name: 'Shackle', rarity: 'uncommon', curse: true, description: 'One tile locks for a turn at the start of every turn.', flavor: 'Something takes hold and will not let go.', hooks: { onTurnStart: [{ type: 'lockTiles', count: 1, turns: 1 }] } },
  { id: 'curse-fester', name: 'Festering', rarity: 'uncommon', curse: true, description: 'One clean tile turns venomous at the start of every turn.', flavor: 'It spreads on its own from here.', hooks: { onTurnStart: [{ type: 'venomTiles', count: 1, value: 1 }] } },
  { id: 'curse-tremor', name: 'Palsy', rarity: 'rare', curse: true, description: 'Every third turn the grid scrambles.', flavor: 'The hand shakes at the worst moment.', hooks: { onTurnStart: [{ type: 'condition', when: { kind: 'turnEvery', value: 3 }, then: [{ type: 'scramble' }] }] } },
];
