/**
 * Placeholder items, named for the cell that carries them (Dean, 2026-09-08: word and
 * evolution themed, not generic). Ten items across five hooks and eight effect types:
 * enough to prove the hook system moves the sim, not to be balanced. Ids are stable; only
 * names and descriptions change, so saves and tests keyed by id survive renames.
 * Rarity weights: see RARITY_WEIGHT.
 */
import type { ItemDef, Rarity } from '../engine/types';

export const RARITY_WEIGHT: Readonly<Record<Rarity, number>> = { common: 3, uncommon: 2, rare: 1, mythic: 0.35 };

export const ITEMS: readonly ItemDef[] = [
  {
    id: 'sharp-pen',
    name: 'Flagellum',
    rarity: 'common',
    description: '+8 damage on every word.',
    flavor: 'A lash behind every syllable.',
    hooks: { onWordScored: [{ type: 'addFlat', value: 8 }] },
  },
  {
    id: 'lens',
    name: 'Photoreceptor',
    rarity: 'uncommon',
    description: '+70% damage.',
    flavor: 'It sees where the weak spot is.',
    hooks: { onWordScored: [{ type: 'addMult', value: 0.7 }] },
  },
  {
    id: 'long-fuse',
    name: 'Ribosome',
    rarity: 'rare',
    description: 'Words of 6+ letters deal double damage.',
    flavor: 'Long chains, long proteins.',
    hooks: {
      onWordScored: [{ type: 'condition', when: { kind: 'minLength', value: 6 }, then: [{ type: 'addMult', value: 1 }] }],
    },
  },
  {
    id: 'vowel-magnet',
    name: 'Vacuole',
    rarity: 'common',
    description: 'Vowels are drawn 80% more often.',
    flavor: 'It stores what you keep running out of.',
    hooks: { onTileDraw: [{ type: 'vowelWeight', value: 1.8 }] },
  },
  {
    id: 'bandage',
    name: 'Mitosis',
    rarity: 'common',
    description: 'Heal 20 after each encounter.',
    flavor: 'Split, recover, continue.',
    hooks: { onEncounterEnd: [{ type: 'heal', value: 20 }] },
  },
  {
    id: 'thick-skin',
    name: 'Membrane',
    rarity: 'uncommon',
    description: 'Take 4 less damage from every hit.',
    flavor: 'Thicker than it looks.',
    hooks: { onDamageTaken: [{ type: 'reduceDamage', value: 4 }] },
  },
  {
    id: 'rare-ink',
    name: 'Enzyme',
    rarity: 'uncommon',
    description: 'J, Q, X and Z are worth +10 each.',
    flavor: 'It catalyses the awkward letters.',
    hooks: { onWordScored: [{ type: 'letterBonus', letters: 'jqxz', value: 10 }] },
  },
  {
    id: 'leech',
    name: 'Cilia',
    rarity: 'uncommon',
    description: 'Heal 4 on every word of 5+ letters.',
    flavor: 'Every long word sweeps in a little life.',
    hooks: {
      onWordScored: [{ type: 'condition', when: { kind: 'minLength', value: 5 }, then: [{ type: 'heal', value: 4 }] }],
    },
  },
  {
    id: 'spores',
    name: 'Spores',
    rarity: 'common',
    description: 'Deal 6 damage to the enemy at the start of each turn.',
    flavor: 'They drift, they land, they burn.',
    hooks: { onTurnStart: [{ type: 'damageEnemy', value: 6 }] },
  },
  // Pool expansion (Dean, 2026-09-08: the first offer was always the same commons). Fourteen
  // more items from the existing vocabulary; rule-benders wait for new effect types.
  {
    id: 'lysosome',
    name: 'Lysosome',
    rarity: 'common',
    description: 'Words of 4 letters or fewer deal +10.',
    flavor: 'Small, sharp, everywhere.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'maxLength', value: 4 }, then: [{ type: 'addFlat', value: 10 }] }] },
  },
  {
    id: 'pilus',
    name: 'Pilus',
    rarity: 'common',
    description: 'Words containing S deal +8.',
    flavor: 'It grips.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'containsLetter', letters: 's' }, then: [{ type: 'addFlat', value: 8 }] }] },
  },
  {
    id: 'chloroplast',
    name: 'Chloroplast',
    rarity: 'common',
    description: 'Heal 3 at the start of every turn.',
    flavor: 'Sunlight, slowly.',
    hooks: { onTurnStart: [{ type: 'heal', value: 3 }] },
  },
  {
    id: 'cell-wall',
    name: 'Cell Wall',
    rarity: 'common',
    description: 'While below half HP, take 6 less damage from every hit.',
    flavor: 'It stiffens under stress.',
    hooks: { onDamageTaken: [{ type: 'condition', when: { kind: 'hpBelow', fraction: 0.5 }, then: [{ type: 'reduceDamage', value: 6 }] }] },
  },
  {
    id: 'nucleus',
    name: 'Nucleus',
    rarity: 'common',
    description: 'Every vowel in a word is worth +3.',
    flavor: 'The centre holds.',
    hooks: { onWordScored: [{ type: 'letterBonus', letters: 'aeiou', value: 3 }] },
  },
  {
    id: 'plasmid',
    name: 'Plasmid',
    rarity: 'common',
    description: 'Every second turn, +70% damage.',
    flavor: 'Borrowed genes, on loan.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'turnEvery', value: 2 }, then: [{ type: 'addMult', value: 0.7 }] }] },
  },
  {
    id: 'peroxisome',
    name: 'Peroxisome',
    rarity: 'uncommon',
    description: 'Words of 5+ letters deal +15.',
    flavor: 'It breaks things down.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'minLength', value: 5 }, then: [{ type: 'addFlat', value: 15 }] }] },
  },
  {
    id: 'golgi',
    name: 'Golgi Body',
    rarity: 'uncommon',
    description: 'L, N, R, S and T are worth +4 each.',
    flavor: 'It packages the ordinary.',
    hooks: { onWordScored: [{ type: 'letterBonus', letters: 'lnrst', value: 4 }] },
  },
  {
    id: 'centriole',
    name: 'Centriole',
    rarity: 'uncommon',
    description: 'Every third turn, deal 18 damage at the start of the turn.',
    flavor: 'It pulls things apart.',
    hooks: { onTurnStart: [{ type: 'condition', when: { kind: 'turnEvery', value: 3 }, then: [{ type: 'damageEnemy', value: 18 }] }] },
  },
  {
    id: 'tentacle',
    name: 'Tentacle',
    rarity: 'common',
    description: 'Words containing J, Q, X or Z deal double damage.',
    flavor: 'Reach for the awkward ones.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'containsLetter', letters: 'jqxz' }, then: [{ type: 'addMult', value: 1 }] }] },
  },
  {
    id: 'symbiont',
    name: 'Symbiont',
    rarity: 'uncommon',
    description: 'Heal 30 after each encounter, but lose 1 HP at the start of every turn.',
    flavor: 'It eats too.',
    hooks: { onEncounterEnd: [{ type: 'heal', value: 30 }], onTurnStart: [{ type: 'damagePlayer', value: 1 }] },
  },
  {
    id: 'apex',
    name: 'Apex Membrane',
    rarity: 'rare',
    description: 'Words of 7+ letters deal triple damage.',
    flavor: 'The top of the food chain.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'minLength', value: 7 }, then: [{ type: 'addMult', value: 2 }] }] },
  },
  {
    id: 'regeneration',
    name: 'Regeneration',
    rarity: 'rare',
    description: 'Heal 1 whenever you take damage.',
    flavor: 'It grows back.',
    hooks: { onDamageTaken: [{ type: 'heal', value: 1 }] },
  },
  {
    id: 'thin-membrane',
    name: 'Thin Membrane',
    rarity: 'rare',
    description: 'Double damage, but every hit you take hurts 4 more.',
    flavor: 'Nothing between you and the world.',
    hooks: { onWordScored: [{ type: 'addMult', value: 1 }], onDamageTaken: [{ type: 'damagePlayer', value: 4 }] },
  },
  {
    id: 'second-wind',
    name: 'Cyst',
    rarity: 'rare',
    description: 'While below 30% HP, heal 3 whenever you take damage.',
    flavor: 'Harden when it hurts.',
    hooks: {
      onDamageTaken: [{ type: 'condition', when: { kind: 'hpBelow', fraction: 0.3 }, then: [{ type: 'heal', value: 3 }] }],
    },
  },
  // Second expansion (Dean, 2026-09-08: "a ton more"). Still the existing vocabulary, combined
  // into identities: thorns, self-venom for power, chaos for damage, cadence gates, HP gates.
  {
    id: 'microtubule',
    name: 'Microtubule',
    rarity: 'common',
    description: 'Words of 5 letters or fewer deal +40%.',
    flavor: 'Short, straight, strong.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'maxLength', value: 5 }, then: [{ type: 'addMult', value: 0.4 }] }] },
  },
  {
    id: 'cytoplasm',
    name: 'Cytoplasm',
    rarity: 'common',
    description: 'Heal 1 at the start of every turn and 10 after each encounter.',
    flavor: 'The medium itself.',
    hooks: { onTurnStart: [{ type: 'heal', value: 1 }], onEncounterEnd: [{ type: 'heal', value: 10 }] },
  },
  {
    id: 'contractile-vacuole',
    name: 'Contractile Vacuole',
    rarity: 'common',
    description: 'Every second turn, heal 3.',
    flavor: 'Pump, release, repeat.',
    hooks: { onTurnStart: [{ type: 'condition', when: { kind: 'turnEvery', value: 2 }, then: [{ type: 'heal', value: 3 }] }] },
  },
  {
    id: 'osmosis',
    name: 'Osmosis',
    rarity: 'common',
    description: 'While below 70% HP, take 2 less damage from every hit.',
    flavor: 'Pressure finds its level.',
    hooks: { onDamageTaken: [{ type: 'condition', when: { kind: 'hpBelow', fraction: 0.7 }, then: [{ type: 'reduceDamage', value: 2 }] }] },
  },
  {
    id: 'histone',
    name: 'Histone',
    rarity: 'common',
    description: 'B, D and G are worth +3 each.',
    flavor: 'It winds the hard letters tight.',
    hooks: { onWordScored: [{ type: 'letterBonus', letters: 'bdg', value: 3 }] },
  },
  {
    id: 'ribbon',
    name: 'Ribbon',
    rarity: 'common',
    description: 'I, N and G are worth +2 each.',
    flavor: 'It ties things together.',
    hooks: { onWordScored: [{ type: 'letterBonus', letters: 'ing', value: 2 }] },
  },
  {
    id: 'stinger',
    name: 'Stinger',
    rarity: 'common',
    description: 'Words containing K or X deal +12.',
    flavor: 'One sharp point.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'containsLetter', letters: 'kx' }, then: [{ type: 'addFlat', value: 12 }] }] },
  },
  {
    id: 'spine',
    name: 'Spine',
    rarity: 'common',
    description: 'Whenever you take damage, deal 5 back.',
    flavor: 'Touch it and see.',
    hooks: { onDamageTaken: [{ type: 'damageEnemy', value: 5 }] },
  },
  {
    id: 'mucus',
    name: 'Mucus',
    rarity: 'common',
    description: 'Take 2 less damage from every hit.',
    flavor: 'Unpleasant, effective.',
    hooks: { onDamageTaken: [{ type: 'reduceDamage', value: 2 }] },
  },
  {
    id: 'buoyancy',
    name: 'Buoyancy',
    rarity: 'common',
    description: 'Vowels are drawn 30% less often, but +40% damage.',
    flavor: 'Denser. Heavier. Harder to spell.',
    hooks: { onTileDraw: [{ type: 'vowelWeight', value: 0.7 }], onWordScored: [{ type: 'addMult', value: 0.4 }] },
  },
  {
    id: 'chitin-plate',
    name: 'Chitin Plate',
    rarity: 'uncommon',
    description: 'Take 5 less damage from every hit.',
    flavor: 'Armour grown, not worn.',
    hooks: { onDamageTaken: [{ type: 'reduceDamage', value: 5 }] },
  },
  {
    id: 'toxin-sac',
    name: 'Toxin Sac',
    rarity: 'uncommon',
    description: '+60% damage, but every fourth turn one of your tiles turns venomous.',
    flavor: 'You are what you secrete.',
    hooks: {
      onWordScored: [{ type: 'addMult', value: 0.6 }],
      onTurnStart: [{ type: 'condition', when: { kind: 'turnEvery', value: 4 }, then: [{ type: 'venomTiles', count: 1, value: 1 }] }],
    },
  },
  {
    id: 'flagellar-motor',
    name: 'Flagellar Motor',
    rarity: 'uncommon',
    description: '+8 damage on every word, but every fifth turn the grid scrambles.',
    flavor: 'It spins. Everything spins.',
    hooks: {
      onWordScored: [{ type: 'addFlat', value: 8 }],
      onTurnStart: [{ type: 'condition', when: { kind: 'turnEvery', value: 5 }, then: [{ type: 'scramble' }] }],
    },
  },
  {
    id: 'hemoglobin',
    name: 'Hemoglobin',
    rarity: 'uncommon',
    description: 'While below half HP, +80% damage.',
    flavor: 'It carries what you need, when you need it.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'hpBelow', fraction: 0.5 }, then: [{ type: 'addMult', value: 0.8 }] }] },
  },
  {
    id: 'antibody',
    name: 'Antibody',
    rarity: 'uncommon',
    description: 'On even turns, take 8 less damage from every hit.',
    flavor: 'It learned last time.',
    hooks: { onDamageTaken: [{ type: 'condition', when: { kind: 'turnEvery', value: 2 }, then: [{ type: 'reduceDamage', value: 8 }] }] },
  },
  {
    id: 'catalase',
    name: 'Catalase',
    rarity: 'uncommon',
    description: 'Words of 5+ letters deal +50%.',
    flavor: 'Faster than it has any right to be.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'minLength', value: 5 }, then: [{ type: 'addMult', value: 0.5 }] }] },
  },
  {
    id: 'lure',
    name: 'Lure',
    rarity: 'uncommon',
    description: 'Words containing Y deal +10 and heal 2.',
    flavor: 'Why? Exactly.',
    hooks: {
      onWordScored: [{ type: 'condition', when: { kind: 'containsLetter', letters: 'y' }, then: [{ type: 'addFlat', value: 10 }, { type: 'heal', value: 2 }] }],
    },
  },
  {
    id: 'membrane-pump',
    name: 'Membrane Pump',
    rarity: 'uncommon',
    description: 'Heal 1 whenever you take damage and 8 after each encounter.',
    flavor: 'In, out, in, out.',
    hooks: { onDamageTaken: [{ type: 'heal', value: 1 }], onEncounterEnd: [{ type: 'heal', value: 8 }] },
  },
  {
    id: 'spore-cloud',
    name: 'Spore Cloud',
    rarity: 'uncommon',
    description: 'Deal 3 damage at the start of each turn and +3 on every word.',
    flavor: 'Everywhere, a little.',
    hooks: { onTurnStart: [{ type: 'damageEnemy', value: 3 }], onWordScored: [{ type: 'addFlat', value: 3 }] },
  },
  {
    id: 'ganglion',
    name: 'Ganglion',
    rarity: 'uncommon',
    description: 'Words of 6+ letters deal +20.',
    flavor: 'A knot of nerve. It remembers the long ones.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'minLength', value: 6 }, then: [{ type: 'addFlat', value: 20 }] }] },
  },
  {
    id: 'metamorphosis',
    name: 'Metamorphosis',
    rarity: 'rare',
    description: '+50% damage and heal 15 after each encounter.',
    flavor: 'Come out of it changed.',
    hooks: { onWordScored: [{ type: 'addMult', value: 0.5 }], onEncounterEnd: [{ type: 'heal', value: 15 }] },
  },
  {
    id: 'hydra',
    name: 'Hydra',
    rarity: 'rare',
    description: 'Whenever you take damage, heal 1 and deal 3 back.',
    flavor: 'Cut it. Go on.',
    hooks: { onDamageTaken: [{ type: 'heal', value: 1 }, { type: 'damageEnemy', value: 3 }] },
  },
  {
    id: 'bioluminescence',
    name: 'Bioluminescence',
    rarity: 'rare',
    description: 'Every vowel is worth +2 and J, Q, X and Z are worth +6 each.',
    flavor: 'It shows off. It has earned it.',
    hooks: { onWordScored: [{ type: 'letterBonus', letters: 'aeiou', value: 2 }, { type: 'letterBonus', letters: 'jqxz', value: 6 }] },
  },
  {
    id: 'apoptosis',
    name: 'Apoptosis',
    rarity: 'rare',
    description: '+150% damage, but lose 3 HP at the start of every turn.',
    flavor: 'Burn bright. Burn.',
    hooks: { onWordScored: [{ type: 'addMult', value: 1.5 }], onTurnStart: [{ type: 'damagePlayer', value: 3 }] },
  },
  {
    id: 'quorum',
    name: 'Quorum',
    rarity: 'rare',
    description: 'Every third turn, triple damage.',
    flavor: 'When enough of you agree.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'turnEvery', value: 3 }, then: [{ type: 'addMult', value: 2 }] }] },
  },
  {
    id: 'stem-cell',
    name: 'Stem Cell',
    rarity: 'rare',
    description: 'Heal 40 after each encounter.',
    flavor: 'It can become anything. Mostly, whole.',
    hooks: { onEncounterEnd: [{ type: 'heal', value: 40 }] },
  },
  // Third expansion (Dean, 2026-09-08: "even more"): fourteen regulars, then the mythic tier.
  {
    id: 'cilium-array',
    name: 'Cilium Array',
    rarity: 'common',
    description: 'Words containing L deal +7.',
    flavor: 'Rows and rows of them, all pulling.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'containsLetter', letters: 'l' }, then: [{ type: 'addFlat', value: 7 }] }] },
  },
  {
    id: 'thylakoid',
    name: 'Thylakoid',
    rarity: 'common',
    description: 'Every third turn, heal 6.',
    flavor: 'Stacked and patient.',
    hooks: { onTurnStart: [{ type: 'condition', when: { kind: 'turnEvery', value: 3 }, then: [{ type: 'heal', value: 6 }] }] },
  },
  {
    id: 'pseudopod',
    name: 'Pseudopod',
    rarity: 'common',
    description: 'Words of 3 letters deal +14.',
    flavor: 'A reach, not a limb.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'maxLength', value: 3 }, then: [{ type: 'addFlat', value: 14 }] }] },
  },
  {
    id: 'sheath',
    name: 'Sheath',
    rarity: 'common',
    description: 'On even turns, take 5 less damage from every hit.',
    flavor: 'It opens and closes.',
    hooks: { onDamageTaken: [{ type: 'condition', when: { kind: 'turnEvery', value: 2 }, then: [{ type: 'reduceDamage', value: 5 }] }] },
  },
  {
    id: 'carotenoid',
    name: 'Carotenoid',
    rarity: 'common',
    description: 'C, H and P are worth +3 each.',
    flavor: 'It gives the colour away.',
    hooks: { onWordScored: [{ type: 'letterBonus', letters: 'chp', value: 3 }] },
  },
  {
    id: 'mycelium',
    name: 'Mycelium',
    rarity: 'uncommon',
    description: 'Heal 2 at the start of every turn and deal 2 damage.',
    flavor: 'It is under everything.',
    hooks: { onTurnStart: [{ type: 'heal', value: 2 }, { type: 'damageEnemy', value: 2 }] },
  },
  {
    id: 'barb',
    name: 'Barb',
    rarity: 'uncommon',
    description: 'Whenever you take damage, deal 9 back.',
    flavor: 'It stays in.',
    hooks: { onDamageTaken: [{ type: 'damageEnemy', value: 9 }] },
  },
  {
    id: 'kinetochore',
    name: 'Kinetochore',
    rarity: 'uncommon',
    description: 'Every second turn, +12 damage and heal 2.',
    flavor: 'It pulls the halves apart on cue.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'turnEvery', value: 2 }, then: [{ type: 'addFlat', value: 12 }, { type: 'heal', value: 2 }] }] },
  },
  {
    id: 'nematocyst',
    name: 'Nematocyst',
    rarity: 'uncommon',
    description: 'Words containing T deal +6 and every vowel is worth +1.',
    flavor: 'Coiled, then not.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'containsLetter', letters: 't' }, then: [{ type: 'addFlat', value: 6 }] }, { type: 'letterBonus', letters: 'aeiou', value: 1 }] },
  },
  {
    id: 'endospore',
    name: 'Endospore',
    rarity: 'uncommon',
    description: 'While below 40% HP, take 7 less damage and heal 2 whenever you take damage.',
    flavor: 'It waits out the bad years.',
    hooks: { onDamageTaken: [{ type: 'condition', when: { kind: 'hpBelow', fraction: 0.4 }, then: [{ type: 'reduceDamage', value: 7 }, { type: 'heal', value: 2 }] }] },
  },
  {
    id: 'lateral-line',
    name: 'Lateral Line',
    rarity: 'rare',
    description: 'Words of 6+ letters deal +30 and heal 5.',
    flavor: 'It feels the long ones coming.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'minLength', value: 6 }, then: [{ type: 'addFlat', value: 30 }, { type: 'heal', value: 5 }] }] },
  },
  {
    id: 'nucleolus',
    name: 'Nucleolus',
    rarity: 'rare',
    description: 'Every letter is worth +2.',
    flavor: 'The factory inside the factory.',
    hooks: { onWordScored: [{ type: 'letterBonus', letters: 'abcdefghijklmnopqrstuvwxyz', value: 2 }] },
  },
  {
    id: 'exoskeleton',
    name: 'Exoskeleton',
    rarity: 'rare',
    description: 'Take 8 less damage from every hit, but vowels are drawn 30% less often.',
    flavor: 'Safe, and stiff.',
    hooks: { onDamageTaken: [{ type: 'reduceDamage', value: 8 }], onTileDraw: [{ type: 'vowelWeight', value: 0.7 }] },
  },
  {
    id: 'lysozyme',
    name: 'Lysozyme',
    rarity: 'rare',
    description: 'Deal 10 damage at the start of every turn.',
    flavor: 'It dissolves walls for a living.',
    hooks: { onTurnStart: [{ type: 'damageEnemy', value: 10 }] },
  },
  // Mythic: explicitly overpowered (Dean, 2026-09-08). Weighted 0.35, so a run sees one about half the time.
  {
    id: 'apex-genome',
    name: 'Apex Genome',
    rarity: 'mythic',
    description: 'Triple damage on every word.',
    flavor: 'Everything that ever ate, in one sequence.',
    hooks: { onWordScored: [{ type: 'addMult', value: 2 }] },
  },
  {
    id: 'immortal-line',
    name: 'Immortal Line',
    rarity: 'mythic',
    description: 'Heal to full after each encounter.',
    flavor: 'It has not died yet. It does not plan to.',
    hooks: { onEncounterEnd: [{ type: 'heal', value: 999 }] },
  },
  {
    id: 'plague',
    name: 'Plague',
    rarity: 'mythic',
    description: 'Deal 25 damage to the enemy at the start of every turn.',
    flavor: 'You did not need the word.',
    hooks: { onTurnStart: [{ type: 'damageEnemy', value: 25 }] },
  },
  {
    id: 'tardigrade',
    name: 'Tardigrade',
    rarity: 'mythic',
    description: 'On even turns, take no damage at all.',
    flavor: 'Boil it. Freeze it. Send it to space. Ask it how it feels.',
    hooks: { onDamageTaken: [{ type: 'condition', when: { kind: 'turnEvery', value: 2 }, then: [{ type: 'reduceDamage', value: 999 }] }] },
  },
  {
    id: 'lexicon',
    name: 'Lexicon',
    rarity: 'mythic',
    description: 'Every letter is worth +6.',
    flavor: 'It knows all the words. It is very smug about it.',
    hooks: { onWordScored: [{ type: 'letterBonus', letters: 'abcdefghijklmnopqrstuvwxyz', value: 6 }] },
  },
  {
    id: 'mirror-membrane',
    name: 'Mirror Membrane',
    rarity: 'mythic',
    description: 'Whenever you take damage, deal 20 back and heal 4.',
    flavor: 'Whatever you are, so is it.',
    hooks: { onDamageTaken: [{ type: 'damageEnemy', value: 20 }, { type: 'heal', value: 4 }] },
  },
  {
    id: 'primordial-soup',
    name: 'Primordial Soup',
    rarity: 'mythic',
    description: 'Vowels are drawn three times as often and +100% damage.',
    flavor: 'Where it all started, still bubbling.',
    hooks: { onTileDraw: [{ type: 'vowelWeight', value: 3 }], onWordScored: [{ type: 'addMult', value: 1 }] },
  },
  {
    id: 'hydrothermal-vent',
    name: 'Hydrothermal Vent',
    rarity: 'mythic',
    description: 'Words of 4 letters or fewer deal +50, and heal 5 at the start of every turn.',
    flavor: 'Life started small and hot.',
    hooks: { onWordScored: [{ type: 'condition', when: { kind: 'maxLength', value: 4 }, then: [{ type: 'addFlat', value: 50 }] }], onTurnStart: [{ type: 'heal', value: 5 }] },
  },
];
